"use client";

interface AISummaryPanelProps {
  summary: string;
  caseType?: string;
  riskLevel?: string;
  humanReviewRequired?: boolean;
}

const caseTypeDescriptions: Record<string, string> = {
  criminal_fraud: "cyber-enabled fraud or account takeover",
  suspicious_transaction: "suspicious transaction / AML-related concern",
  data_breach: "possible personal data breach",
  internal_review: "internal compliance review",
};

export default function AISummaryPanel({
  summary,
  caseType,
  riskLevel,
  humanReviewRequired,
}: AISummaryPanelProps) {
  const typeLabel = caseType ? caseTypeDescriptions[caseType] || caseType.replace("_", " ") : null;

  return (
    <div
      style={{
        background: "rgba(6,182,212,0.06)",
        border: "1px solid rgba(6,182,212,0.18)",
        borderRadius: "12px",
        padding: "1.25rem 1.5rem",
      }}
    >
      {/* Section heading */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "1rem" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "0.625rem" }}>
          <div
            style={{
              width: "28px",
              height: "28px",
              borderRadius: "7px",
              background: "rgba(6,182,212,0.15)",
              border: "1px solid rgba(6,182,212,0.3)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              fontSize: "0.9rem",
            }}
          >
            🤖
          </div>
          <h4
            style={{
              fontSize: "0.8rem",
              fontWeight: 700,
              color: "#06b6d4",
              textTransform: "uppercase",
              letterSpacing: "0.07em",
              margin: 0,
            }}
          >
            AI-Generated Case Summary
          </h4>
        </div>

        <div
          style={{
            padding: "0.25rem 0.625rem",
            background: "rgba(6,182,212,0.12)",
            border: "1px solid rgba(6,182,212,0.25)",
            borderRadius: "5px",
            fontSize: "0.625rem",
            fontWeight: 700,
            color: "#22d3ee",
            letterSpacing: "0.06em",
          }}
        >
          DRAFT — ANALYST REVIEW REQUIRED
        </div>
      </div>

      {/* Summary text */}
      <p
        style={{
          fontSize: "0.9375rem",
          color: "var(--text-secondary)",
          lineHeight: "1.7",
          marginBottom: typeLabel ? "1rem" : 0,
        }}
      >
        {summary || "No AI summary available for this case. The summary will be generated once the case is processed by the backend."}
      </p>

      {/* Category context */}
      {typeLabel && (
        <div
          style={{
            marginTop: "0.875rem",
            padding: "0.75rem 1rem",
            background: "rgba(0,0,0,0.15)",
            borderRadius: "8px",
            borderLeft: "3px solid rgba(6,182,212,0.5)",
          }}
        >
          <div style={{ fontSize: "0.6875rem", color: "#06b6d4", fontWeight: 700, letterSpacing: "0.06em", marginBottom: "0.25rem" }}>
            CASE CLASSIFICATION
          </div>
          <p style={{ fontSize: "0.8125rem", color: "var(--text-secondary)", margin: 0 }}>
            This case has been categorised as <strong style={{ color: "var(--text-primary)" }}>{typeLabel}</strong>.
            {humanReviewRequired
              ? " Human analyst review is mandatory before any escalation or external submission."
              : " This case is recommended for internal documentation."}
          </p>
        </div>
      )}

      {/* Compliance disclaimer */}
      <div
        style={{
          marginTop: "0.875rem",
          display: "flex",
          alignItems: "flex-start",
          gap: "0.5rem",
          padding: "0.625rem 0.875rem",
          background: "rgba(0,0,0,0.2)",
          borderRadius: "7px",
        }}
      >
        <span style={{ fontSize: "0.75rem", color: "var(--text-muted)", marginTop: "0.05rem" }}>ℹ</span>
        <p style={{ fontSize: "0.6875rem", color: "var(--text-muted)", lineHeight: 1.6, margin: 0 }}>
          This summary was generated by the FraudGuard AI model. It is intended as a professional operations note to
          assist analyst investigation — not as a legal determination or final accusation. All conclusions require
          human review and compliance approval before any external reporting or escalation action is taken.
        </p>
      </div>
    </div>
  );
}
